### ISSUE TITLE
one simple question about the EGS algorithm

### ISSUE THREAD

**Issue by zark721** [binqi-sun/egs#1]
Dear bingqi,
I am currently reading your paper titled "Edge Generation Scheduling for DAG Tasks using Deep Reinforcement Learning" and I must say it's quite insightful. However, I am confused regarding Algorithm 2(The EGS framework).

In Algorithm 2, it states that the loop continues while "<ins>M</ins> < W(G)". Based on my understanding of the paper context and the source code provided on GitHub, I am inclined to believe that the loop condition should be "<ins>M</ins> < W(G')", where G' represents the latest generated graph.

Could you please confirm whether my interpretation is correct? I would greatly appreciate any clarification you could provide on this matter.

I got the paper pdf from https://ieeexplore.ieee.org/abstract/document/10382409 

Thank you very much for your time and attention.

**Comment by binqi-sun** [comment]
Hi there,

Thank you very much for noticing this typo. I confirm that your understanding is correct, and it should be `W(G')` instead of `W(G)`. 

Please feel free to let us know if you have any further questions. 

Binqi

**Comment by zark721** [comment]
Thank you for your prompt response. Here are two more questions:

1. In `Theorem 5.1 (Length constraint)`, it states 't<sub>i</sub><sup>EFT</sup> equals the length of the longest path between the source node and vi'. However, I believe the WCET (worst-case execution time) of vi should be added to this value. Could you confirm whether this modification is required? If so, should the subsequent proof be adjusted accordingly?

2. Regarding Example 7 of `5.4 Example of edge generation policy`, it appears that the description does not align with the illustration from Fig 7a to Fig 7c. Specifically, edge(3,5) seems redundant in the original DAG, suggesting that the mask matrix M would not allow the addition of edge(3,5).

**Comment by binqi-sun** [comment]
1. The length of a path is defined as the sum WCET of the nodes included in the path. The WCET of `v_i` is indeed included in the path length. There is no need to adjust the proof. 

2. From Fig. 7a to Fig. 7c, edge (3,4) is added rather than edge (3,5). The description in the figure caption is correct, but the description in Example 7 should be adjusted.

**Comment by zark721** [comment]
Thanks bingqi,
Do you plan to open-source your reinforcement learning neural network design?
It would be valuable for the community, including myself.

**Comment by binqi-sun** [comment]
Thank you for your interest in our work! Yes, we plan to open-source the neural network design codes. Please stay tuned for the updates in this repository.
